const MIN_USERNAME_LENGTH = 4
const MAX_USERNAME_LENGTH = 20
const MIN_PASSWORD_LENGTH = 6
const MAX_PASSWORD_LENGTH = 50
const MAX_TITLE_LENGTH = 30
const MIN_TITLE_LENGTH = 0
const MIN_BODY_LENGTH = 0
const MAX_BODY_LENGTH = 200
const MIN_TAGS_LENGTH = 4
const MAX_TAGS_LENGTH = 30
const OBJECT_ID_LENGTH = 24

module.exports = {
    MIN_USERNAME_LENGTH,
    MAX_USERNAME_LENGTH,
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
    MAX_TITLE_LENGTH,
    MIN_TITLE_LENGTH,
    MIN_BODY_LENGTH,
    MAX_BODY_LENGTH,
    MIN_TAGS_LENGTH,
    MAX_TAGS_LENGTH,
    OBJECT_ID_LENGTH
}